#!/usr/bin/perl -I/usr/depot/lib/perlxt
#
# connect to a Tor ControlPort, receive events and generate PSYC messages
# CAUTION: WORK IN PROGRESS

use Getopt::Std;
getopt('bp');

die <<X unless $opt_p;
Usage: $0 -p <password> 
X

	print <<X;
AUTHENTICATE "$opt_p"
SETEVENTS CIRC STATUS_CLIENT STATUS_GENERAL STATUS_SERVER
X
# SIGNAL NEWNYM
# getinfo circuit-status
# getinfo stream-status

				# make the library sweat a little
my $uni = $opt_b || "psyc://$ENV{USER}\@127.0.0.1:4251/\$psycontor";

use Net::PSYC qw( :event );

bind_uniform( $uni );
register_uniform();

sub type {
    my $bla = <STDIN>;
    print <<X;
you typed: $bla
bye.
X
    exit;
}

# shows how to do add own fds into the select-wrapper
add(\*STDIN, 'r', \&type);

sub msg {
    my ($source, $mc, $data, $vars) = @_;

    if ($vars) {
	    print <<X;

variables:
X
	    foreach $i (keys %$vars) {
		    print "\t$i $vars->{$i}\n";
	    }
    }
    if ($data) {
	    if (length($data) < 200) {
		    print <<X;
==============================================================================
$data
==============================================================================
X
	    } elsif (open(O, ">dump")) {
		    print O $data;
		    close O;
		    print "\n", length($data), <<X;
bytes of data stored in a file called 'dump'
X
	    } else {
		    print STDERR <<X;
could not save data in a file called 'dump': $!
X
	    }
    }
    print "\nlistening... ";
}

$|=1;
print "\nlistening on $uni ... ";

start_loop();

